fix build error (on windows) related to translation.ts
fixes:
src/api/middlewares/Translation.ts:36:10 - error TS2769: No overload matches this call.
  Overload 1 of 2, '(callback?: Callback | undefined): Promise<TFunction<"translation", undefined>>', gave the following error.
    Object literal may only specify known properties, and 'preload' does not exist in type 'Callback'.
  Overload 2 of 2, '(options: InitOptions<{ loadPath: string; }>, callback?: Callback | undefined): Promise<TFunction<"translation", undefined>>', gave the following error.
    Object literal may only specify known properties, and 'showSupportNotice' does not exist in type 'InitOptions<{ loadPath: string; }>'.

36         .init({